version: 2.1

references:
  container_config: &container_config
    docker:
      # Main Python container
      - image: circleci/python:3.8.3
        environment:
          TARGET_VERTICA_HOST: test_vertica
          TARGET_VERTICA_PORT: 5433
          TARGET_VERTICA_USER: dbadmin
          TARGET_VERTICA_PASSWORD: secret
          TARGET_VERTICA_DBNAME: docker
          TARGET_VERTICA_SCHEMA: myschema

      # Vertica service container image used as test source database
      - image: jbfavre/vertica
        name: test_vertica
        environment:
          DATABASE_PASSWORD: secret

jobs:
  build:
    <<: *container_config

    steps:
      - checkout

      - run:
          name: 'Setup virtual environment'
          command: |
            python3 -m venv ./virtualenvs/target-vertica
            . ./virtualenvs/target-vertica/bin/activate
            pip install --upgrade pip
            pip install -e .[test]

      - run:
          name: 'Pylinting'
          command: |
            . ./virtualenvs/target-vertica/bin/activate
            pylint --rcfile .pylintrc --disable duplicate-code target_vertica/

      - run:
          name: 'Unit Tests'
          command: |
            . ./virtualenvs/target-vertica/bin/activate
            export LOGGING_CONF_FILE=$(pwd)/sample_logging.conf
            dockerize -wait tcp://test_vertica:5433 -timeout 1m
            nosetests --where=tests/unit

      - run:
          name: 'Integration Tests'
          command: |
            . ./virtualenvs/target-vertica/bin/activate
            export LOGGING_CONF_FILE=$(pwd)/sample_logging.conf
            nosetests --where=tests/integration/

workflows:
  version: 2
  build:
    jobs:
      - build